import type { Lead } from '@/types'

const DAY = 86400000
const HOUR = 3600000
const now = () => Date.now()

export function buildSampleLeads(): Lead[] {
  return [
    {
      id: '1',
      name: 'Sarah & Tom Henderson',
      eventType: 'wedding',
      eventDate: '2026-03-14',
      guestCount: 120,
      contactMethod: 'email',
      stage: 'post-visit',
      estimatedValue: 18500,
      depositAmount: null,
      enquiryDate: new Date(now() - 10 * DAY).toISOString(),
      lastContact: new Date(now() - 3 * DAY).toISOString(),
      visitDate: new Date(now() - 3 * DAY).toISOString(),
      followUpDue: new Date(now() - 1 * DAY).toISOString(),
      depositReceived: false,
      room: 'manukau',
      notes:
        'Loved the garden area. Concerned about pricing vs Wintergarden. Said deciding by end of week.',
      competingVenues: ['Wintergarden'],
      source: 'Google',
    },
    {
      id: '2',
      name: 'Auckland Council',
      eventType: 'corporate',
      eventDate: '2026-06-18',
      guestCount: 80,
      contactMethod: 'email',
      stage: 'contacted',
      estimatedValue: 12000,
      depositAmount: null,
      enquiryDate: new Date(now() - 7 * DAY).toISOString(),
      lastContact: new Date(now() - 5 * DAY).toISOString(),
      visitDate: null,
      followUpDue: null,
      depositReceived: false,
      room: 'pohutukawa',
      notes: 'Annual team dinner. Needs AV setup. Checking two other venues.',
      competingVenues: ['Cordis Hotel', 'Ellerslie Event Centre'],
      source: 'Referral',
    },
    {
      id: '3',
      name: 'Faleolo Family',
      eventType: 'funeral',
      eventDate: new Date(now() + 5 * DAY).toISOString().split('T')[0],
      guestCount: 60,
      contactMethod: 'phone',
      stage: 'confirmed',
      estimatedValue: 4500,
      depositAmount: 4500,
      enquiryDate: new Date(now() - 4 * DAY).toISOString(),
      lastContact: new Date(now() - 2 * DAY).toISOString(),
      visitDate: null,
      followUpDue: null,
      depositReceived: true,
      room: 'somerset',
      notes:
        'Deposit received. Catering confirmed. Family very grateful — keep comms warm and simple.',
      competingVenues: [],
      source: 'Referral',
    },
    {
      id: '4',
      name: 'Pacific Health Trust',
      eventType: 'corporate',
      eventDate: '2026-08-12',
      guestCount: 200,
      contactMethod: 'email',
      stage: 'visit-booked',
      estimatedValue: 22000,
      depositAmount: null,
      enquiryDate: new Date(now() - 5 * DAY).toISOString(),
      lastContact: new Date(now() - 1 * DAY).toISOString(),
      visitDate: new Date(now() + 1 * DAY).toISOString(),
      followUpDue: null,
      depositReceived: false,
      room: 'manukau',
      notes:
        'Annual conference. CEO presenting. Needs stage, PA, projector. High value — prioritise.',
      competingVenues: ['ASB Waterfront Theatre'],
      source: 'LinkedIn',
    },
    {
      id: '5',
      name: 'Emma & Liam Taufa',
      eventType: 'wedding',
      eventDate: '2027-01-22',
      guestCount: 150,
      contactMethod: 'social',
      stage: 'new',
      estimatedValue: 20000,
      depositAmount: null,
      enquiryDate: new Date(now() - 2 * HOUR).toISOString(),
      lastContact: new Date(now() - 2 * HOUR).toISOString(),
      visitDate: null,
      followUpDue: null,
      depositReceived: false,
      room: null,
      notes: 'Instagram DM. Summer wedding. Mentioned Cornwall Park specifically.',
      competingVenues: [],
      source: 'Instagram',
    },
    {
      id: '6',
      name: 'Tui Celebrations',
      eventType: 'private',
      eventDate: '2026-09-05',
      guestCount: 40,
      contactMethod: 'email',
      stage: 'contacted',
      estimatedValue: 5500,
      depositAmount: null,
      enquiryDate: new Date(now() - 11 * DAY).toISOString(),
      lastContact: new Date(now() - 9 * DAY).toISOString(),
      visitDate: null,
      followUpDue: null,
      depositReceived: false,
      room: 'somerset',
      notes: '50th birthday. Want afternoon tea setup. Gone quiet since initial reply.',
      competingVenues: [],
      source: 'Google',
    },
  ]
}
