import type { GlossaryEntry, ReviewStatus } from './types';

const d: ReviewStatus = { status: 'draft', reviewer: null, review_date: null };
const dv: ReviewStatus = { status: 'draft', reviewer: null, review_date: null, varies_by_nuu: true };

export const glossary: GlossaryEntry[] = [
  {
    id: 'aiga',
    term: 'Aiga',
    pronunciation: 'EYE-ngah',
    meaning_en: 'Family — in the extended sense, including all descendants and connected lines, not just the household.',
    meaning_sm: 'O le aiga atoa, e aofia ai uso, tuagane, ma le gafa atoa, ae le na o le aiga vavalalata.',
    related: ['aiga-potopoto'],
    review: d,
  },
  {
    id: 'aiga-potopoto',
    term: 'Aiga potopoto',
    pronunciation: 'EYE-ngah poh-toh-POH-toh',
    meaning_en: 'The whole extended family gathered — the decision-making body of the aiga.',
    meaning_sm: 'O le aiga atoa ua potopoto — o le aoao e faia fa\'ai\'uga mo le aiga.',
    related: ['aiga', 'fono'],
    review: d,
  },
  {
    id: 'alii',
    term: "Ali'i",
    pronunciation: 'ah-LEE-ee',
    meaning_en: "A chief — one of the two main classes of matai. Ali'i represent the dignity and lineage of the title.",
    meaning_sm: "Ali'i — o se tasi o vasega muamua e lua o matai. E fa'aali e ali'i le mamalu ma le gafa o le suafa.",
    related: ['matai', 'tulafale'],
    review: d,
  },
  {
    id: 'ava',
    term: "'Ava",
    pronunciation: 'AH-vah',
    meaning_en: "Kava — the ceremonial drink prepared from the root of Piper methysticum. The 'ava ceremony opens formal matai gatherings.",
    meaning_sm: "'Ava — o le mea inu paia ua palu mai i le a'a o le 'ava. E tatala ai aofia o matai.",
    related: ['taupou', 'taufa', 'tanoa'],
    review: d,
  },
  {
    id: 'faalavelave',
    term: "Fa'alavelave",
    pronunciation: 'fah-ah-lah-veh-LAH-veh',
    meaning_en: "A major family obligation — most often a funeral, wedding, saofa'i, or other family event requiring contribution. Both the event and the contribution are called fa'alavelave.",
    meaning_sm: "O se fa'alavelave i le aiga — e masani ai i maliu, fa'aipoipoga, saofa'i, ma isi mea e mana'omia ai se fesoasoani. E ta'ua le sauniga ma le fesoasoani o le fa'alavelave.",
    related: ['ietoga', 'aiga-potopoto'],
    review: dv,
  },
  {
    id: 'faamatai',
    term: "Fa'amatai",
    pronunciation: 'fah-ah-mah-TYE',
    meaning_en: "The chiefly system — the social and political structure of Samoa, organising aiga and nu'u under matai.",
    meaning_sm: "O le fa'amatai — o le faiga ma le faasoasoa o aiga ma nu'u i Sāmoa, e ta'ita'i e matai.",
    related: ['matai', 'fono', 'nuu'],
    review: d,
  },
  {
    id: 'faaipoipoga',
    term: "Fa'aipoipoga",
    pronunciation: 'fah-ah-ee-poy-POH-ngah',
    meaning_en: 'Wedding ceremony.',
    meaning_sm: 'O le sauniga o le fa\'aipoipoga.',
    related: [],
    review: d,
  },
  {
    id: 'faifeau',
    term: "Faife'au",
    pronunciation: 'fah-ee-FEH-au',
    meaning_en: 'Minister of the church. Holds significant authority alongside the matai in village life.',
    meaning_sm: 'O le ta\'ita\'i o le ekalesia. E tāua lona pule fa\'atasi ma matai i le ola o le nu\'u.',
    related: [],
    review: d,
  },
  {
    id: 'faipule',
    term: 'Faipule',
    pronunciation: 'fye-POO-leh',
    meaning_en: 'A village representative — historically, a matai who held a political/legislative role.',
    meaning_sm: 'O se sui o le nu\'u — o se matai sa umia se tofi fa\'apolokiki.',
    related: ['matai'],
    review: d,
  },
  {
    id: 'fono',
    term: 'Fono',
    pronunciation: 'FOH-noh',
    meaning_en: 'A formal meeting — of the village (fono a le nu\'u), of the aiga, or of the country.',
    meaning_sm: 'O se fonotaga aloa\'ia — o le nu\'u, o le aiga, po o le atunu\'u.',
    related: ['matai', 'nuu'],
    review: d,
  },
  {
    id: 'ifoga',
    term: 'Ifoga',
    pronunciation: 'ee-FOH-ngah',
    meaning_en: 'A ceremonial act of contrition in which the offending aiga sits under fine mats at the home of the offended aiga, awaiting acceptance and forgiveness.',
    meaning_sm: 'O le sauniga o le fa\'aleleiga, e nonofo ai le aiga ua sese i lalo o \'ie tōga i le aiga ua sese i ai, e fa\'atali se\'i talia.',
    related: ['ietoga'],
    review: d,
  },
  {
    id: 'ietoga',
    term: "'Ie toga / 'Ie tōga",
    pronunciation: 'EE-eh TOH-ngah',
    meaning_en: 'Fine mats — the highest cultural currency in Samoa, woven from pandanus, presented at every major fa\'alavelave.',
    meaning_sm: "O 'ie tōga — o le mea sili ona tāua i le aganu'u Sāmoa, e lalaga i le lau o le paogo, e tu'uina atu i fa'alavelave.",
    related: ['faalavelave'],
    review: d,
  },
  {
    id: 'lauga',
    term: 'Lauga',
    pronunciation: 'lah-OO-ngah',
    meaning_en: 'A formal Samoan oratorical speech — opens and closes every formal gathering. Follows a strict order: God, the place, the matai, the family, the matter at hand.',
    meaning_sm: "O le lauga aloa'ia — e tatala ma fa'ai'u ai so'o se aofia aloa'ia. E mulimuli i le fa'asologa: le Atua, le nofoaga, matai, le aiga, ma le mataupu.",
    related: ['tulafale'],
    review: d,
  },
  {
    id: 'manaia',
    term: 'Manaia',
    pronunciation: 'mah-NYE-ah',
    meaning_en: "The ceremonial son of a chief — counterpart to the taupou. Holds an honoured place in the procession.",
    meaning_sm: "O le atalii fa'aaloalogia o se matai — e tutusa ma le taupou. E iai lona nofoaga fa'aaloalogia.",
    related: ['taupou'],
    review: d,
  },
  {
    id: 'matai',
    term: 'Matai',
    pronunciation: 'mah-TYE',
    meaning_en: 'A holder of a Samoan chiefly title. Matai are responsible to their aiga and to their village.',
    meaning_sm: 'O lē e umia se suafa Sāmoa. E i ai le tiute o matai i lo latou aiga ma le nu\'u.',
    related: ['alii', 'tulafale', 'saofai'],
    review: d,
  },
  {
    id: 'nuu',
    term: "Nu'u",
    pronunciation: 'NOO-oo',
    meaning_en: 'Village. The fundamental unit of Samoan social structure.',
    meaning_sm: 'O le nu\'u — o le iunite muamua o le faasoasoa o le aganu\'u Sāmoa.',
    related: ['fono', 'matai'],
    review: d,
  },
  {
    id: 'saofai',
    term: "Saofa'i",
    pronunciation: 'sah-oh-FYE',
    meaning_en: "The ceremony of bestowing a matai title.",
    meaning_sm: "O le sauniga o le tu'uina atu o se suafa matai.",
    related: ['matai'],
    review: dv,
  },
  {
    id: 'sao',
    term: "Sa'o",
    pronunciation: 'SAH-oh',
    meaning_en: "The head matai of an aiga — holds the senior title and authority.",
    meaning_sm: "O le matai sili o se aiga — e umia le suafa maualuga ma le pule.",
    related: ['matai', 'aiga'],
    review: d,
  },
  {
    id: 'tanoa',
    term: 'Tanoa',
    pronunciation: 'tah-NOH-ah',
    meaning_en: "Carved wooden bowl in which the 'ava is prepared.",
    meaning_sm: "O le ipu la'au tofitofi e palu ai le 'ava.",
    related: ['ava'],
    review: d,
  },
  {
    id: 'taufa',
    term: 'Taufa',
    pronunciation: 'TAU-fah',
    meaning_en: "The person who mixes the 'ava — often the taupou.",
    meaning_sm: "O le tagata e palu le 'ava — e masani lava ona avea ma taupou.",
    related: ['ava', 'taupou'],
    review: d,
  },
  {
    id: 'taupou',
    term: 'Taupou',
    pronunciation: 'TAU-poh-oo',
    meaning_en: "The ceremonial daughter of a chief — traditional preparer of the 'ava and ceremonial representative.",
    meaning_sm: "O le afafine fa'aaloalogia o se matai — e masani ona palu le 'ava ma fai ma sui aloa'ia.",
    related: ['manaia', 'ava'],
    review: d,
  },
  {
    id: 'toona',
    term: "To'ona'i",
    pronunciation: 'toh-oh-NAH-ee',
    meaning_en: 'The Sunday lunch — the weekly family meal after church.',
    meaning_sm: 'O le taumafataga o le Aso Sa ina ua mae\'a le lotu.',
    related: [],
    review: d,
  },
  {
    id: 'tulafale',
    term: 'Tulafale',
    pronunciation: 'too-lah-FAH-leh',
    meaning_en: "Talking chief / orator. Tulafale carry the speech rights and ceremonial knowledge of the aiga.",
    meaning_sm: "Tulafale — o le matai e fofogaina lauga ma fa'aali le poto o le aganu'u o le aiga.",
    related: ['matai', 'alii', 'lauga'],
    review: d,
  },
  {
    id: 'umu',
    term: 'Umu',
    pronunciation: 'OO-moo',
    meaning_en: 'The traditional above-ground earth oven of hot stones — the Samoan way of cooking the Sunday meal.',
    meaning_sm: 'O le umu — o le fa\'asaga masani Sāmoa e fa\'aogāina ma\'a vevela e vela ai le taumafataga o le Aso Sa.',
    related: ['toona'],
    review: d,
  },
  {
    id: 'tautua',
    term: 'Tautua',
    pronunciation: 'tau-TOO-ah',
    meaning_en: 'Service. The cultural value of serving one\'s aiga and village — the path to leadership runs through tautua.',
    meaning_sm: 'O le tautua — o le fa\'aaogāina o le tagata mo le aiga ma le nu\'u. O le ala i le pule, o le tautua.',
    related: [],
    review: d,
  },
];

export const glossaryById = Object.fromEntries(glossary.map((g) => [g.id, g]));
